
-- DROP TABLE DCALAMVIEC
CREATE TABLE DCALAMVIEC (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	TILELUONG DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT INTEG_374 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY78 ON DCALAMVIEC (ID);

-- DROP TABLE DCHITIEUCHITIET

CREATE TABLE DCHITIEUCHITIET (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DCHITIEUDOANHTHUID VARCHAR(36),
	DTINHTHANHID VARCHAR(36),
	CHITIEU DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT INTEG_449 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY95 ON DCHITIEUCHITIET (ID);

-- DROP TABLE DCHITIEUDOANHTHU
CREATE TABLE DCHITIEUDOANHTHU (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	DNHOMCHITIEUDOANHTHUID VARCHAR(36),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	NAM INTEGER DEFAULT 0,
	THANG1 DECIMAL(18,2) DEFAULT 0,
	THANG2 DECIMAL(18,2) DEFAULT 0,
	THANG3 DECIMAL(18,2) DEFAULT 0,
	THANG4 DECIMAL(18,2) DEFAULT 0,
	THANG5 DECIMAL(18,2) DEFAULT 0,
	THANG6 DECIMAL(18,2) DEFAULT 0,
	THANG7 DECIMAL(18,2) DEFAULT 0,
	THANG8 DECIMAL(18,2) DEFAULT 0,
	THANG9 DECIMAL(18,2) DEFAULT 0,
	THANG10 DECIMAL(18,2) DEFAULT 0,
	THANG11 DECIMAL(18,2) DEFAULT 0,
	THANG12 DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT INTEG_440 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY93 ON DCHITIEUDOANHTHU (ID);

-- DROP TABLE DCUAHANG

CREATE TABLE DCUAHANG (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	DIACHI VARCHAR(255),
	DIENTHOAI VARCHAR(255),
	DKHOHANGID VARCHAR(36),
	STEMPLATEID VARCHAR(36),
	CONSTRAINT INTEG_416 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY87 ON DCUAHANG (ID);

-- DROP TABLE DDINHLUONG

CREATE TABLE DDINHLUONG (
	NOTE VARCHAR(255),
	DMATHANGID VARCHAR(36),
	SOLUONG DECIMAL(18,2),
	DVATTUID VARCHAR(36),
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	CONSTRAINT INTEG_459 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY98 ON DDINHLUONG (ID);

-- DROP TABLE DDOITACKYGUI

CREATE TABLE DDOITACKYGUI (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	HOAHONG DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT INTEG_411 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY86 ON DDOITACKYGUI (ID);

-- DROP TABLE DDONVITINH

CREATE TABLE DDONVITINH (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	SORTORDER VARCHAR(255),
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_326 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY67 ON DDONVITINH (ID);

-- DROP TABLE DDOTKHUYENMAI

CREATE TABLE DDOTKHUYENMAI (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DLOAIHINHKHUYENMAIID VARCHAR(36),
	TUNGAY TIMESTAMP,
	DENNGAY TIMESTAMP,
	NGUNGAPDUNG INTEGER DEFAULT 0,
	TILEGIAMGIA DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT INTEG_274 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY56 ON DDOTKHUYENMAI (ID);

-- DROP TABLE DDOTKHUYENMAICHITIET

CREATE TABLE DDOTKHUYENMAICHITIET (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DDOTKHUYENMAIID VARCHAR(36),
	DNHOMMATHANGID VARCHAR(36),
	TILEGIAMGIA DECIMAL(18,2) DEFAULT 0,
	DMATHANGID VARCHAR(36),
	GIABAN DECIMAL(18,2) DEFAULT 0,
	GIATRIDONHANG DECIMAL(18,2) DEFAULT 0,
	SOLUONGMATHANG DECIMAL(18,2) DEFAULT 0,
	SOLUONGMUA DECIMAL(18,2) DEFAULT 0,
	SOLUONGTANG DECIMAL(18,2) DEFAULT 0,
	DMATHANGTANGID VARCHAR(36),
	CONSTRAINT INTEG_369 PRIMARY KEY (ID)
);
CREATE INDEX DDOTKHUYENMAICHITIET_DMATHANGID ON DDOTKHUYENMAICHITIET ();
CREATE UNIQUE INDEX RDB$PRIMARY77 ON DDOTKHUYENMAICHITIET (ID);

-- DROP TABLE DHANGSANXUAT
CREATE TABLE DHANGSANXUAT (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_244 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY50 ON DHANGSANXUAT (ID);

-- DROP TABLE DKHACHHANG

CREATE TABLE DKHACHHANG (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	DNHOMKHACHHANGID VARCHAR(36),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	MAKHACH VARCHAR(255),
	DIACHI VARCHAR(255),
	DIENTHOAI VARCHAR(255),
	EMAIL VARCHAR(255),
	MASOTHUE VARCHAR(255),
	DNHANVIENID VARCHAR(36),
	NGAYSINH TIMESTAMP,
	DIEMTICHLUYBANDAU INTEGER DEFAULT 0,
	GIABAN INTEGER DEFAULT 0,
	DTINHTHANHID VARCHAR(36),
	FACEBOOK VARCHAR(255),
	CONSTRAINT INTEG_259 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY53 ON DKHACHHANG (ID);

-- DROP TABLE DKHOHANG

CREATE TABLE DKHOHANG (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CHOPHEPAMKHO INTEGER DEFAULT 0,
	DCUAHANGID VARCHAR(36),
	CONSTRAINT INTEG_249 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY51 ON DKHOHANG (ID);

-- DROP TABLE DLOAIHINHKHUYENMAI

CREATE TABLE DLOAIHINHKHUYENMAI (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_269 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY55 ON DLOAIHINHKHUYENMAI (ID);

-- DROP TABLE DLOAIQUY
CREATE TABLE DLOAIQUY (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	SORTORDER VARCHAR(255),
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_469 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY100 ON DLOAIQUY (ID);

-- DROP TABLE DLYDOTHUCHI

CREATE TABLE DLYDOTHUCHI (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	LALYDOTHU INTEGER,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	SORTORDER VARCHAR(255),
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	LOAILYDO INTEGER DEFAULT 0,
	CONSTRAINT INTEG_306 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY63 ON DLYDOTHUCHI (ID);

-- DROP TABLE DLYDOTHUONGPHAT

CREATE TABLE DLYDOTHUONGPHAT (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_384 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY80 ON DLYDOTHUONGPHAT (ID);

-- DROP TABLE DMATHANG

CREATE TABLE DMATHANG (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	CODE VARCHAR(255),
	GIANHAP DECIMAL(18,2),
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	GIABAN DECIMAL(18,2) DEFAULT 0,
	GIABAN2 DECIMAL(18,2) DEFAULT 0,
	GIABAN3 DECIMAL(18,2) DEFAULT 0,
	GIABAN4 DECIMAL(18,2) DEFAULT 0,
	TONTOITHIEU DECIMAL(18,2) DEFAULT 0,
	TONTOIDA DECIMAL(18,2) DEFAULT 0,
	BAOHANH VARCHAR(255),
	MASANCO VARCHAR(255),
	DHANGSANXUATID VARCHAR(36),
	ANH BLOB SUB_TYPE 0,
	HOAHONG DECIMAL(18,2) DEFAULT 0,
	GIAVON DECIMAL(18,2) DEFAULT 0,
	DDONVITINHCHANID VARCHAR(36),
	GIABANCHAN DECIMAL(18,2) DEFAULT 0,
	DDOITACKYGUIID VARCHAR(36),
	MACDINHGIAMGIA DECIMAL(18,2) DEFAULT 0,
	MACDINHGIAMTIEN DECIMAL(18,2) DEFAULT 0,
	DNHOMMATHANGID VARCHAR(36),
	DDONVITINHID VARCHAR(36),
	QUYDOI DECIMAL(18,2),
	THEOCAN INTEGER,
	COHANSUDUNG INTEGER,
	LOAIDINHLUONG INTEGER,
	"SIZE" VARCHAR(255),
	CONSTRAINT INTEG_321 PRIMARY KEY (ID)
);
CREATE INDEX DMATHANG_DDONVITINHID ON DMATHANG ();
CREATE INDEX DMATHANG_DNHOMMATHANGID ON DMATHANG ();
CREATE UNIQUE INDEX RDB$PRIMARY66 ON DMATHANG (ID);

-- DROP TABLE DNHACUNGCAP

CREATE TABLE DNHACUNGCAP (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	DNHOMNHACUNGCAPID VARCHAR(36),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	MANHACUNGCAP VARCHAR(255),
	DIACHI VARCHAR(255),
	DIENTHOAI VARCHAR(255),
	EMAIL VARCHAR(255),
	WEBSITE VARCHAR(255),
	CONSTRAINT INTEG_337 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY70 ON DNHACUNGCAP (ID);

-- DROP TABLE DNHANVIEN

CREATE TABLE DNHANVIEN (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CACHTINHLUONG INTEGER DEFAULT 0,
	NGHITHU7 INTEGER DEFAULT 0,
	NGHICHUNHAT INTEGER DEFAULT 0,
	LUONGCA DECIMAL(18,2) DEFAULT 0,
	LUONGTHANG DECIMAL(18,2) DEFAULT 0,
	DIACHI VARCHAR(255),
	DIENTHOAI VARCHAR(255),
	CONSTRAINT INTEG_264 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY54 ON DNHANVIEN (ID);

-- DROP TABLE DNHOMCHITIEUDOANHTHU

CREATE TABLE DNHOMCHITIEUDOANHTHU (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_435 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY92 ON DNHOMCHITIEUDOANHTHU (ID);

-- DROP TABLE DNHOMKHACHHANG

CREATE TABLE DNHOMKHACHHANG (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	TILEGIAMGIA DECIMAL(18,2) DEFAULT 0,
	DIEMTICHLUY DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT INTEG_254 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY52 ON DNHOMKHACHHANG (ID);

-- DROP TABLE DNHOMMATHANG

CREATE TABLE DNHOMMATHANG (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	SORTORDER VARCHAR(255),
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CODE VARCHAR(255),
	CONSTRAINT INTEG_316 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY65 ON DNHOMMATHANG (ID);

-- DROP TABLE DNHOMNHACUNGCAP
CREATE TABLE DNHOMNHACUNGCAP (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_332 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY69 ON DNHOMNHACUNGCAP (ID);

-- DROP TABLE DNHOMTHETRATRUOC

CREATE TABLE DNHOMTHETRATRUOC (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	SORTORDER VARCHAR(255),
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_479 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY102 ON DNHOMTHETRATRUOC (ID);

-- DROP TABLE DNHOMVOUCHER

CREATE TABLE DNHOMVOUCHER (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	SORTORDER VARCHAR(255),
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_464 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY99 ON DNHOMVOUCHER (ID);

-- DROP TABLE DTAIKHOANNGANHANG

CREATE TABLE DTAIKHOANNGANHANG (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_455 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY97 ON DTAIKHOANNGANHANG (ID);

-- DROP TABLE DTHETRATRUOC

CREATE TABLE DTHETRATRUOC (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	DNHOMTHETRATRUOCID VARCHAR(36),
	KHOA INTEGER,
	NGAYHETHAN TIMESTAMP,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	CONSTRAINT INTEG_484 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY103 ON DTHETRATRUOC (ID);

-- DROP TABLE DTINHTHANH

CREATE TABLE DTINHTHANH (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	SORTORDER VARCHAR(255),
	USERCREATEDID VARCHAR(36) NOT NULL,
	PARENTID VARCHAR(36),
	PARENTDIR VARCHAR(255),
	ITEMTYPE INTEGER,
	AUTOID BIGINT,
	SIMAGEID VARCHAR(36),
	CONSTRAINT INTEG_445 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY94 ON DTINHTHANH (ID);

-- DROP TABLE DVOUCHER

CREATE TABLE DVOUCHER (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	DNHOMVOUCHERID VARCHAR(36),
	GIATRI DECIMAL(18,2),
	NGAYPHATHANH TIMESTAMP,
	HANSUDUNG TIMESTAMP,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	CONSTRAINT INTEG_474 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY101 ON DVOUCHER (ID);

-- DROP TABLE TBANGLUONG

CREATE TABLE TBANGLUONG (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	NGAY TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	THANG INTEGER DEFAULT 0,
	NAM INTEGER DEFAULT 0,
	CHITIET BLOB SUB_TYPE 0,
	CONSTRAINT INTEG_393 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY82 ON TBANGLUONG (ID);

-- DROP TABLE TBANGLUONGCHITIET

CREATE TABLE TBANGLUONGCHITIET (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	TBANGLUONGID VARCHAR(36),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DNHANVIENID VARCHAR(36),
	DCALAMVIECID VARCHAR(36),
	TRANGTHAI INTEGER DEFAULT 0,
	NGAY TIMESTAMP,
	CONSTRAINT INTEG_388 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY81 ON TBANGLUONGCHITIET (ID);

-- DROP TABLE TBANGLUONGTONGHOP

CREATE TABLE TBANGLUONGTONGHOP (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DNHANVIENID VARCHAR(36),
	LUONGCA DECIMAL(18,2) DEFAULT 0,
	TONGLUONG DECIMAL(18,2) DEFAULT 0,
	PHAT DECIMAL(18,2) DEFAULT 0,
	TAMUNG DECIMAL(18,2) DEFAULT 0,
	THUCNHAN DECIMAL(18,2) DEFAULT 0,
	THUONG DECIMAL(18,2) DEFAULT 0,
	LUONGTHANG DECIMAL(18,2) DEFAULT 0,
	CACHTINHLUONG INTEGER DEFAULT 0,
	TBANGLUONGID VARCHAR(36),
	CONSTRAINT INTEG_397 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY83 ON TBANGLUONGTONGHOP (ID);

-- DROP TABLE TBAOGIA

CREATE TABLE TBAOGIA (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	NGAY TIMESTAMP,
	TENKHACH VARCHAR(255),
	DIACHI VARCHAR(255),
	DIENTHOAI VARCHAR(255),
	EMAIL VARCHAR(255),
	TIENHANG DECIMAL(18,2),
	TILETHUE DECIMAL(18,2),
	TIENTHUE DECIMAL(18,2),
	TILEGIAMGIA DECIMAL(18,2),
	TIENGIAMGIA DECIMAL(18,2),
	PHIVANCHUYEN DECIMAL(18,2),
	TONGCONG DECIMAL(18,2),
	LOAI INTEGER,
	GIAMTHEOTIEN INTEGER,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DKHACHHANGID VARCHAR(36),
	CONSTRAINT INTEG_292 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY60 ON TBAOGIA (ID);

-- DROP TABLE TBAOGIACHITIET

CREATE TABLE TBAOGIACHITIET (
	NOTE VARCHAR(255),
	SOLUONG DECIMAL(18,2),
	DONGIA DECIMAL(18,2),
	THANHTIEN DECIMAL(18,2),
	TILEGIAMGIA DECIMAL(18,2),
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DDONVITINHID VARCHAR(36),
	TBAOGIAID VARCHAR(36),
	DMATHANGID VARCHAR(36),
	CONSTRAINT INTEG_287 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY59 ON TBAOGIACHITIET (ID);

-- DROP TABLE TCHITIETTHANHTOAN

CREATE TABLE TCHITIETTHANHTOAN (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	TDONHANGID VARCHAR(36),
	TTHUCHIID VARCHAR(36),
	SOTIEN DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT INTEG_430 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY91 ON TCHITIETTHANHTOAN (ID);

-- DROP TABLE TDATHANG

CREATE TABLE TDATHANG (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	NGAY TIMESTAMP,
	TENKHACH VARCHAR(255),
	DIACHI VARCHAR(255),
	DIENTHOAI VARCHAR(255),
	EMAIL VARCHAR(255),
	TIENHANG DECIMAL(18,2),
	TILETHUE DECIMAL(18,2),
	TIENTHUE DECIMAL(18,2),
	TILEGIAMGIA DECIMAL(18,2),
	TIENGIAMGIA DECIMAL(18,2),
	PHIVANCHUYEN DECIMAL(18,2),
	TONGCONG DECIMAL(18,2),
	LOAI INTEGER,
	GIAMTHEOTIEN INTEGER,
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DKHACHHANGID VARCHAR(36),
	LOAIGIA INTEGER DEFAULT 0,
	CONSTRAINT INTEG_301 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY62 ON TDATHANG (ID);

-- DROP TABLE TDATHANGCHITIET

CREATE TABLE TDATHANGCHITIET (
	NOTE VARCHAR(255),
	SOLUONG DECIMAL(18,2),
	DONGIA DECIMAL(18,2),
	THANHTIEN DECIMAL(18,2),
	TILEGIAMGIA DECIMAL(18,2),
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	BAOHANH VARCHAR(255),
	DDONVITINHID VARCHAR(36),
	TDATHANGID VARCHAR(36),
	DMATHANGID VARCHAR(36),
	CONSTRAINT INTEG_296 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY61 ON TDATHANGCHITIET (ID);

-- DROP TABLE TDONHANG

CREATE TABLE TDONHANG (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	NGAY TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	GIAMTHEOTIEN INTEGER DEFAULT 0,
	LOAI INTEGER DEFAULT 0,
	TONGCONG DECIMAL(18,2) DEFAULT 0,
	PHIVANCHUYEN DECIMAL(18,2) DEFAULT 0,
	TIENGIAMGIA DECIMAL(18,2) DEFAULT 0,
	TILEGIAMGIA DECIMAL(18,2) DEFAULT 0,
	TIENTHUE DECIMAL(18,2) DEFAULT 0,
	TILETHUE DECIMAL(18,2) DEFAULT 0,
	TIENHANG DECIMAL(18,2) DEFAULT 0,
	DNHACUNGCAPID VARCHAR(36),
	DKHOXUATID VARCHAR(36),
	DKHONHAPID VARCHAR(36),
	DNHANVIENXUATID VARCHAR(36),
	DNHANVIENNHAPID VARCHAR(36),
	DIENGIAI VARCHAR(255),
	GIOTHANHTOAN TIMESTAMP,
	KHACHDUA DECIMAL(18,2) DEFAULT 0,
	TRALAI DECIMAL(18,2) DEFAULT 0,
	NOCU DECIMAL(18,2) DEFAULT 0,
	LANIN INTEGER DEFAULT 0,
	LOAIGIA INTEGER DEFAULT 0,
	USERTHANHTOANID VARCHAR(36),
	TIENTHANHTOAN DECIMAL(18,2) DEFAULT 0,
	LOAITHANHTOAN INTEGER DEFAULT 0,
	TDATHANGID VARCHAR(36),
	GIAOHANG VARCHAR(255),
	DATHANHTOAN INTEGER DEFAULT 0,
	DOITRA DECIMAL(18,2) DEFAULT 0,
	CONNO INTEGER DEFAULT 0,
	DIEM DECIMAL(18,2) DEFAULT 0,
	VOUCHER DECIMAL(18,2) DEFAULT 0,
	DNHANVIENGIAOID VARCHAR(36),
	TRICHNHANVIEN DECIMAL(18,2) DEFAULT 0,
	DCUAHANGID VARCHAR(36),
	CONLAI DECIMAL(18,2) DEFAULT 0,
	THANHTOAN DECIMAL(18,2) DEFAULT 0,
	DKHACHHANGID VARCHAR(36),
	DTAIKHOANNGANHANGID VARCHAR(36),
	THETRATRUOC DECIMAL(18,2),
	TRUTICHLUY DECIMAL(18,2),
	DIEMGIAM DECIMAL(18,2),
	TIENMAT DECIMAL(18,2),
	CHUYENKHOAN DECIMAL(18,2),
	THE DECIMAL(18,2),
	DVOUCHERID VARCHAR(36),
	DTHETRATRUOCID VARCHAR(36),
	CONSTRAINT INTEG_346 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY72 ON TDONHANG (ID);
CREATE INDEX TDONHANG_DKHACHHANGID ON TDONHANG ();
CREATE INDEX TDONHANG_DNHACUNGCAPID ON TDONHANG ();

-- DROP TABLE TDONHANGCHITIET

CREATE TABLE TDONHANGCHITIET (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	TDONHANGID VARCHAR(36),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DMATHANGID VARCHAR(36),
	BAOHANH VARCHAR(255),
	TILEGIAMGIA DECIMAL(18,2) DEFAULT 0,
	THANHTIEN DECIMAL(18,2) DEFAULT 0,
	DONGIA DECIMAL(18,2) DEFAULT 0,
	SLNHAP DECIMAL(18,4) DEFAULT 0,
	SLXUAT DECIMAL(18,4) DEFAULT 0,
	SLTHUCTE DECIMAL(18,4) DEFAULT 0,
	SLHETHONG DECIMAL(18,4) DEFAULT 0,
	DKHOHANGID VARCHAR(36),
	KHUYENMAI INTEGER DEFAULT 0,
	DDONVITINHID VARCHAR(36),
	SLNHAPCHUAQUYDOI DECIMAL(18,4) DEFAULT 0,
	SLXUATCHUAQUYDOI DECIMAL(18,4) DEFAULT 0,
	GIAMTHEOTIEN INTEGER DEFAULT 0,
	TIENGIAMGIA DECIMAL(18,2) DEFAULT 0,
	TDONHANGTRAID VARCHAR(36),
	XUATVATTU INTEGER,
	KICHTHUOC VARCHAR(255),
	HANSUDUNG TIMESTAMP,
	CONSTRAINT INTEG_341 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY71 ON TDONHANGCHITIET (ID);
CREATE INDEX TDONHANGCHITIET_DDONVITINHID ON TDONHANGCHITIET ();
CREATE INDEX TDONHANGCHITIET_DMATHANGID ON TDONHANGCHITIET ();
CREATE INDEX TDONHANGCHITIET_TDONHANGID ON TDONHANGCHITIET ();

-- DROP TABLE TDONHANGHUY

CREATE TABLE TDONHANGHUY (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	NGAY TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	KHACHHANG VARCHAR(255),
	NHANVEN VARCHAR(255),
	THUNGAN VARCHAR(255),
	DOITRA DECIMAL(18,2) DEFAULT 0,
	DATHANHTOAN INTEGER DEFAULT 0,
	GIOTHANHTOAN TIMESTAMP,
	TRALAI DECIMAL(18,2) DEFAULT 0,
	TIENHANG DECIMAL(18,2) DEFAULT 0,
	TILETHUE DECIMAL(18,2) DEFAULT 0,
	TIENTHUE DECIMAL(18,2) DEFAULT 0,
	TILEGIAMGIA DECIMAL(18,2) DEFAULT 0,
	TIENGIAMGIA DECIMAL(18,2) DEFAULT 0,
	PHIVANCHUYEN DECIMAL(18,2) DEFAULT 0,
	THANHTOANBOI VARCHAR(255),
	NGAYHUY TIMESTAMP,
	GIOHUY TIMESTAMP,
	CONSTRAINT INTEG_406 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY85 ON TDONHANGHUY (ID);

-- DROP TABLE TDONHANGHUYCHITIET

CREATE TABLE TDONHANGHUYCHITIET (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	TDONHANGHUYID VARCHAR(36),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	MAHANG VARCHAR(255),
	TENHANG VARCHAR(255),
	DVT VARCHAR(255),
	DONGIA DECIMAL(18,2) DEFAULT 0,
	THANHTIEN DECIMAL(18,2) DEFAULT 0,
	SOLUONG DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT INTEG_401 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY84 ON TDONHANGHUYCHITIET (ID);

-- DROP TABLE TLUUTAM

CREATE TABLE TLUUTAM (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	NGAY TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DOITRA DECIMAL(18,2) DEFAULT 0,
	GIAOHANG VARCHAR(255),
	TDATHANGID VARCHAR(36),
	LOAIGIA INTEGER DEFAULT 0,
	DIENGIAI VARCHAR(255),
	DNHANVIENXUATID VARCHAR(36),
	DKHOXUATID VARCHAR(36),
	TIENHANG DECIMAL(18,2) DEFAULT 0,
	TILETHUE DECIMAL(18,2) DEFAULT 0,
	TIENTHUE DECIMAL(18,2) DEFAULT 0,
	TILEGIAMGIA DECIMAL(18,2) DEFAULT 0,
	TIENGIAMGIA DECIMAL(18,2) DEFAULT 0,
	PHIVANCHUYEN DECIMAL(18,2) DEFAULT 0,
	TONGCONG DECIMAL(18,2) DEFAULT 0,
	GIAMTHEOTIEN INTEGER DEFAULT 0,
	DKHACHHANGID VARCHAR(36),
	CONSTRAINT INTEG_355 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY74 ON TLUUTAM (ID);

-- DROP TABLE TLUUTAMCHITIET

CREATE TABLE TLUUTAMCHITIET (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	TLUUTAMID VARCHAR(36),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	SOLUONG DECIMAL(18,4) DEFAULT 0,
	DONGIA DECIMAL(18,2) DEFAULT 0,
	THANHTIEN DECIMAL(18,2) DEFAULT 0,
	TILEGIAMGIA DECIMAL(18,2) DEFAULT 0,
	BAOHANH VARCHAR(255),
	DMATHANGID VARCHAR(36),
	DDONVITINHID VARCHAR(36),
	SOLUONGCHUAQUYDOI DECIMAL(18,4),
	CONSTRAINT INTEG_350 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY73 ON TLUUTAMCHITIET (ID);

-- DROP TABLE TLUUVET

CREATE TABLE TLUUVET (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	NGAY TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	GIO TIMESTAMP,
	SODONHANG VARCHAR(36),
	TAIKHOAN VARCHAR(36),
	CONSTRAINT INTEG_360 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY75 ON TLUUVET (ID);

-- DROP TABLE TNGUOIDUNGTHEOCUAHANG

CREATE TABLE TNGUOIDUNGTHEOCUAHANG (
	ID VARCHAR(36) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	SUSERID VARCHAR(36),
	DCUAHANGID VARCHAR(36),
	CONSTRAINT INTEG_420 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY88 ON TNGUOIDUNGTHEOCUAHANG (ID);

-- DROP TABLE TTANGGIAMDIEM

CREATE TABLE TTANGGIAMDIEM (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	NGAY TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DKHACHHANGID VARCHAR(36),
	DIEMTANG DECIMAL(18,2) DEFAULT 0,
	DIEMGIAM DECIMAL(18,2) DEFAULT 0,
	LYDO VARCHAR(255),
	CONSTRAINT INTEG_365 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY76 ON TTANGGIAMDIEM (ID);

-- DROP TABLE TTHUCHI

CREATE TABLE TTHUCHI (
	NOTE VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	NGAY TIMESTAMP,
	TENDOITUONG VARCHAR(255),
	DIACHI VARCHAR(255),
	LOAI INTEGER,
	LOAIDOITUONG INTEGER,
	DIENGIAI VARCHAR(255),
	CHUNGTUGOC VARCHAR(255),
	THU DECIMAL(18,2),
	CHI DECIMAL(18,2),
	ID VARCHAR(36) NOT NULL,
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DNHACUNGCAPID VARCHAR(36),
	CHUYENKHOAN INTEGER DEFAULT 0,
	LATAMUNG INTEGER DEFAULT 0,
	TBANGLUONGID VARCHAR(36),
	TDATHANGID VARCHAR(36),
	DCUAHANGID VARCHAR(36),
	LAPHIEUTHUCONGNO INTEGER DEFAULT 0,
	KHONGTHAYDOICONGNO INTEGER DEFAULT 0,
	DNHANVIENID VARCHAR(36),
	DKHACHHANGID VARCHAR(36),
	DLYDOTHUCHIID VARCHAR(36),
	DTAIKHOANNGANHANGID VARCHAR(36),
	DTHETRATRUOCID VARCHAR(36),
	CONSTRAINT INTEG_311 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY64 ON TTHUCHI (ID);
CREATE INDEX TTHUCHI_DKHACHHANGID ON TTHUCHI ();
CREATE INDEX TTHUCHI_DLYDOTHUCHIID ON TTHUCHI ();
CREATE INDEX TTHUCHI_DNHACUNGCAPID ON TTHUCHI ();

-- DROP TABLE TTHUONGPHAT

CREATE TABLE TTHUONGPHAT (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	NOTE VARCHAR(255),
	STATUS INTEGER NOT NULL,
	USERMODIFIEDID VARCHAR(36),
	TIMEMODIFIED TIMESTAMP,
	TIMECREATED TIMESTAMP,
	NGAY TIMESTAMP,
	USERCREATEDID VARCHAR(36) NOT NULL,
	DNHANVIENID VARCHAR(36),
	THUONG DECIMAL(18,2) DEFAULT 0,
	PHAT DECIMAL(18,2) DEFAULT 0,
	DLYDOTHUONGPHATID VARCHAR(36),
	CONSTRAINT INTEG_379 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY79 ON TTHUONGPHAT (ID);
